version: "3.9"

services:

  worker:

    build: .

    environment:
     API_ID: $API_ID
     API_HASH: $API_HASH
     TG_BOT_TOKEN: $TG_BOT_TOKEN
     AUTH_CHANNEL: $AUTH_CHANNEL
     OWNER_ID: $OWNER_ID
     DATABASE_URI: $DATABASE_URI
     DATABASE_NAME: $DATABASE_NAME
     CHANNELS: $CHANNELS
     ADMINS: $ADMINS
     LOG_CHANNEL: $LOG_CHANNEL
